### PR TITLE
HEVC Encode - Reduce video size by ~69%

### PR DESCRIPTION
**Pull request by jonfairbanks**
I HEVC encoded the video files for both the 1080p and 4k versions.

This reduced the files size by:
- 4k: 69.5%
- 1080p: 69.1%

Please merge and release a new build and I'd be happy to help test it out.  

**Note:** I think something is wrong with the source file for the 1080p version. The aspect ratio seems to be off. It is squished horizontally.

Thank you!

### CODE REVIEW

**Comment by jonfairbanks** [comment]
When on mobile, you may see loading/stuttering when playing the original 4k version depending on your connection speed. Re-encoding to make these videos smaller will hopefully help.

**Comment by modem7** [comment]
The source 1080p version was just a transcode from the 4k to 1080p (likely chance I did something wrong during transcoding w/ Handbrake). So if you'd like to totally redo the 1080 version, you may get better quality/aspect ratio on that front!

Will rebuild the new versions now.

https://drone.modem7.com/modem7/docker-rickroll/153 current build status

**Comment by modem7** [comment]
All tags have been rebuilt and ready for testing @jonfairbanks! 

Massive image size difference, great job!

**Comment by jonfairbanks** [comment]
@modem7 Can we roll these changes back? I'm sad to say browsers seemingly do not support HEVC encoded video.

Screenshot_13

I'll need to look around to see if there is a better browser side encoding format.

**Comment by modem7** [comment]
No worries! Will do! 

I wonder if webm or ogg format would work better?

Edit: All reverted

**Comment by jonfairbanks** [comment]
@modem7 Did the 4k version get reverted as well? Looks like that is still using the old file.

Thanks again!

**Comment by modem7** [comment]
Heya, I'm not rebuilding the 4k version at 500mb unfortunately.

Github LFS charges on bandwidth and at 500mb it causes additional charges/mucks with my other projects for the rest of the month.

If you'd like, I can grab the original file again?

**Comment by modem7** [comment]
FYI, I used a yt-dlp container to grab

```yaml
Check video and audio format code:
$ docker run --rm tnk4on/yt-dlp -F <url>

Create download dir and set codes:
$ mkdir -p /my/download/dir/
$ VIDEO=137 # choose video code from above command
$ AUDIO=140 # choose audio code from above command
$ URL=<url>

Download video:
$ docker run --rm \
       -v <downloadDIR>:/media \
       tnk4on/yt-dlp \
       -f ${VIDEO}+${AUDIO} --merge-output-format mp4 ${URL}
```

Then used a 3 minute version of the link you suggested: https://www.youtube.com/watch?v=o-YBDTqX_ZU

For 1080, video code 399 and audio code 139 would be suitable.
For 4k, video code 401 and audio code 139 would be suitable.

**Comment by jonfairbanks** [comment]
Ahh gotcha, I wasn't aware this was costing. Certainly don't impact other projects for Rick. 😆

Also thank you for sharing the Docker setup. This is relevant for something else I was working on as well.

**Comment by modem7** [comment]
@jonfairbanks — Annoyingly, it only costs w/ the 4k version! With the 1080p version, I can keep it under their 1gb cap per month (with a monthly rebuild of all containers)

Just had a quick thought though: 

Until we can figure out a lower sized version, mount a local version of the 4k rickroll.mp4 to /usr/share/nginx/html/rickroll.mp4

So something like:

```yaml
# Rickroll
  rickroll:
    image: modem7/docker-rickroll
    container_name: Rickroll
    networks:
      pihole:
    volumes:
      - /local/location/rickroll.mp4:/usr/share/nginx/html/rickroll.mp4:ro
    labels: 
      - autoheal=true
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.rickroll-rtr.entrypoints=https"
      - "traefik.http.routers.rickroll-rtr.rule=Host(`rickroll.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.rickroll-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.rickroll-rtr.service=rickroll-svc"
      - "traefik.http.services.rickroll-svc.loadbalancer.server.port=80"
    restart: always
```

**Pull request merged**
